declare module "akaneko";
declare module "pokedex-promise-v2";
declare module "lolis.life";
declare module "mathjs";
declare module "node-fetch";
declare module "genshin-db";
declare module "shentai";
declare module "mywaifulist-scraper";
declare module "mangadex-full-api";
declare module "mal-scraper";
declare module "wikipedia";
declare module "anime-wallpaper";
declare module "translate-google";
declare module "trace.moe.ts";
declare module "animequotes";
declare module "canvacord";
declare module "discord-image-generation";
declare module "cheerio";
declare module "anilist-node";
declare module "mailist";
declare module "@marsron/google-image";
declare module "emoji-api";
declare module "node-periodic-table";
declare module "oakdex-pokedex";
declare module "ptable";
declare module "node-myanimelist";
declare module 'public-waifulist'
declare module '@freezegold/anime.js'
declare module "mangadex-full-api";
declare module "mal-scraper";
declare module "wikipedia";
declare module "better-tord";
declare module "anime-wallpapers";
declare module "translate-google";
declare module "animequotes";
declare module "mailist";
declare module "node-periodic-table";
declare module "oakdex-pokedex";
declare module "ptable";
declare module "node-myanimelist";
declare module "genius-lyrics";
declare module "trace.moe.ts";
declare module "anilist-node";
declare module 'imgbb-uploader'
declare module 'text-from-image'

